In [35]:
%matplotlib widget

In [119]:
import pandas as pd
import numpy as np
from glob import glob
import os
import datetime
import matplotlib.pyplot as plt

from tensorflow.keras.layers import Input, Concatenate, Dot, Add, ReLU, Activation
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras import layers
from tensorflow.keras.optimizers import Adam
import tensorflow as tf
from tensorflow import keras

In [70]:
plt.figure(figsize=(10, 8))

t1 = [[1,2,3,4,5,6]]
print(t1)
t1 = tf.reshape(t1,[2,3])
print(t1)
t1 = tf.reduce_mean(t1,1)
print(t1)



plt.plot([1,2,3,4],[1,2,3,4])
plt.scatter([1,2,3,4],[2.5,2.5,2.5,2.5], label='Labels', c='#2ca02c')
plt.scatter([4,3,2,1],[3.5,3.0,2.5,2.0], marker=None, label='Predictions', c='#ff7f0e')



plt.show()


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[[1, 2, 3, 4, 5, 6]]
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)


In [128]:
x = layers.Lambda(lambda x:x**2)
x

x(5)


<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [98]:
x = tf.Variable(range(0,10,2), tf.float32)

print(x)

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 2, 4, 6, 8], dtype=int32)>


In [104]:
input_data = [1,2,3]
x = tf.placeholder(dtype=tf.float32)
#y=x*2
#sess=tf.Session()
#print(sess.run(y,feed_dict={x:input_data}))

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [31]:
folder = 'data'
# file_names = [['가평_2016.xlsx','가평_2017.xlsx','가평_2018.xlsx', '가평_2019.xlsx'], 
#               ['의암호_2016.xlsx','의암호_2017.xlsx','의암호_2018.xlsx', '의암호_2019.xlsx'],
#               ['서상_2016.xlsx','서상_2017.xlsx','서상_2018.xlsx', '서상_2019.xlsx']]

file_names = [['가평_2016.xlsx','가평_2017.xlsx','가평_2018.xlsx', '가평_2019.xlsx'], 
              ['의암호_2016.xlsx','의암호_2017.xlsx','의암호_2018.xlsx', '의암호_2019.xlsx']]
day = 24*60*60
year = (365.2425)*day

df_full = []
df = []

for loc in range(len(file_names)):
    
    df_loc = []
    for y in range(len(file_names[loc])):
        path = os.path.join(folder, file_names[loc][y])
        print(file_names[loc][y])
        df_loc.append(pd.read_excel(path))
    df_full.append(pd.concat(df_loc))
    df.append(df_full[loc].iloc[:, [2,3,4,5,6,7,10]])
    

df = df_full[0].copy()

df
    
    
#date_time = pd.to_datetime(df_full[0])
#timestamp_s = date_time.map(datetime.datetime.timestamp)
#df['Day sin'] = np.sin(timestamp_s * (2 * np.pi / day))
#df['Day cos'] = np.cos(timestamp_s * (2 * np.pi / day))
#df['Year sin'] = np.sin(timestamp_s * (2 * np.pi / year))
#df['Year cos'] = np.cos(timestamp_s * (2 * np.pi / year))


#    date_time = pd.to_datetime(df_full[loc].iloc[:, 0], format='%Y.%m.%d %H:%M', utc=True)
#    timestamp_s = date_time.map(datetime.datetime.timestamp)
    #df[loc]['Day sin'] = np.sin(timestamp_s * (2 * np.pi / day))
    #df[loc]['Day cos'] = np.cos(timestamp_s * (2 * np.pi / day))
    #df[loc]['Year sin'] = np.sin(timestamp_s * (2 * np.pi / year))
    #df[loc]['Year cos'] = np.cos(timestamp_s * (2 * np.pi / year))
    #df[loc] = df[loc].reset_index(drop=True)

가평_2016.xlsx
가평_2017.xlsx
가평_2018.xlsx
가평_2019.xlsx
의암호_2016.xlsx
의암호_2017.xlsx
의암호_2018.xlsx
의암호_2019.xlsx


측정날짜 측정소명   수온  수소이온농도  전기전도도  용존산소   탁도  총유기탄소    총질소  \
0     2016.01.01 00:00   가평  4.5     7.5  126.0  10.8  0.6    1.4  2.398   
1     2016.01.01 01:00   가평  4.3     7.5  126.0  10.8  0.5    1.4  2.490   
2     2016.01.01 02:00   가평  4.4     7.5  126.0  10.8  0.5    1.4  2.545   
3     2016.01.01 03:00   가평  4.4     7.5  126.0  10.8  0.6    1.4  2.482   
4     2016.01.01 04:00   가평  4.4     7.5  126.0  10.8  0.6    1.4  2.453   
...                ...  ...  ...     ...    ...   ...  ...    ...    ...   
8755  2019.12.31 19:00   가평  3.6     7.1  115.0  12.6  1.1    1.8  1.718   
8756  2019.12.31 20:00   가평  3.5     7.1  115.0  12.6  1.1    1.7  1.726   
8757  2019.12.31 21:00   가평  3.4     7.1  115.0  12.6  1.1    1.7  1.738   
8758  2019.12.31 22:00   가평  3.4     7.1  115.0  12.6  1.1    1.7  1.723   
8759  2019.12.31 23:00   가평  3.3     7.1  115.0  12.6  1.0    1.7  1.705   

         총인  클로로필-a  미생물_독성지수  
0     0.006     5.7       0.5  
1     0.003     5.4       0.4  
2     0.003     5.4       0.5  
3     0.002     5.4       4.7  
4     0.003     5.4      -2.5  
...     ...     ...       ...  
8755  0.002    22.7       0.1  
8756  0.001    21.9       0.5  
8757  0.002    21.3       0.9  
8758  0.002    21.5       0.7  
8759  0.002    20.9       0.8  

[35064 rows x 12 columns]